export const sectors = [
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'technology', label: 'Technology' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'finance', label: 'Finance' },
  { value: 'energy', label: 'Energy' },
  { value: 'retail', label: 'Retail' },
]

export const stages = [
  { value: 'rd', label: 'R&D' },
  { value: 'prototype', label: 'Prototype' },
  { value: 'production', label: 'Production' },
  { value: 'scaling', label: 'Scaling' },
  { value: 'maintenance', label: 'Maintenance' },
]

export const tools = [
  { value: 'siemens-nx', label: 'Siemens NX', company: 'Siemens Digital Industries Software' },
  { value: 'autodesk-fusion', label: 'Autodesk Fusion 360', company: 'Autodesk' },
  { value: 'solidworks', label: 'SolidWorks', company: 'Dassault Systemes' },
  { value: 'catia', label: 'CATIA', company: 'Dassault Systemes' },
  { value: 'inventor', label: 'Inventor', company: 'Autodesk' },
  { value: 'creo', label: 'Creo', company: 'PTC' },
]

export const audiences = [
  { value: 'board', label: 'Board / Executive Sponsor' },
  { value: 'technical', label: 'Technical Team' },
  { value: 'operations', label: 'Operations Manager' },
  { value: 'procurement', label: 'Procurement Team' },
  { value: 'it', label: 'IT Department' },
]

export const featureCategories = [
  { value: 'strategic-market', label: 'Strategic & Market Alignment' },
  { value: 'technical-capability', label: 'Technical Capability' },
  { value: 'integration', label: 'Integration & Ecosystem' },
  { value: 'cost-roi', label: 'Cost & ROI Analysis' },
  { value: 'security-compliance', label: 'Security & Compliance' },
]

export const weightModes = [
  { value: 'static', label: 'Static (Default Weights)', description: 'Use predefined weightings' },
  { value: 'user', label: 'User Based', description: 'Customize weights based on preferences' },
  { value: 'dynamic', label: 'Dynamic (AI Optimized)', description: 'AI adjusts weights automatically' },
]

export const sampleReports: Record<string, string> = {
  'siemens-nx': `# Manufacturing R&D Analysis Report
## Tool: Siemens NX (Siemens Digital Industries Software)

### Executive Summary
Siemens NX is a leading integrated CAD/CAM/CAE software suite that provides comprehensive digital twin capabilities for manufacturing enterprises. This report analyzes its strategic fit for R&D operations in the manufacturing sector.

---

## 1. Strategic & Market Alignment

### Market Position
Siemens NX holds a **strong market position** in the enterprise manufacturing segment, with particular strength in:
- Automotive industry (40% market share)
- Aerospace and defense (35% adoption rate)
- Industrial machinery (45% penetration)

### Competitive Advantages
| Feature | Siemens NX | Industry Average |
|---------|-----------|------------------|
| CAD/CAM Integration | Excellent | Good |
| Simulation Capabilities | Advanced | Moderate |
| PLM Integration | Native | Plugin-based |
| Cloud Deployment | Hybrid | Limited |

---

## 2. Technical Capability Assessment

### Core Features Score: 9.2/10
- **Generative Design**: Advanced AI-powered design exploration
- **Advanced Simulation**: Full-spectrum FEA and CFD analysis
- **Manufacturing Integration**: Seamless CAM workflows
- **Data Management**: Integrated Teamcenter support

### Performance Metrics
\`\`\`
Model Complexity Support: Up to 100M+ faces
Assembly Size: Unlimited components
Rendering Speed: Real-time with RTX support
Cloud Scalability: Linear performance scaling
\`\`\`

---

## 3. ROI Analysis

### Initial Investment
- License Cost: $$$$ (Enterprise tier)
- Implementation: 6-12 months
- Training: 40-80 hours per user

### Expected Returns
- **Design Cycle Reduction**: 30-40%
- **Error Reduction**: 50-60%
- **Collaboration Efficiency**: 45% improvement
- **Time-to-Market**: 25% faster

---

## 4. Recommendations

### For Board/Executive Sponsors:
1. **Approve phased implementation** starting with R&D department
2. **Allocate budget** for comprehensive training program
3. **Establish KPIs** for measuring adoption success
4. **Plan for integration** with existing PLM systems

### Risk Mitigation
- Ensure adequate IT infrastructure
- Plan for change management
- Consider hybrid deployment model

---

*Report generated by ResearchAI on ${new Date().toLocaleDateString()}*
`,
  'autodesk-fusion': `# Manufacturing R&D Analysis Report
## Tool: Autodesk Fusion 360 (Autodesk)

### Executive Summary
Autodesk Fusion 360 is a cloud-based 3D CAD, CAM, and CAE platform that offers an integrated approach to product development. This report evaluates its suitability for manufacturing R&D operations.

---

## 1. Strategic & Market Alignment

### Market Position
Fusion 360 has gained significant traction in the SMB and mid-market segments:
- Small to Medium Business: 55% adoption rate
- Startups & Innovation Labs: 65% preference
- Educational Institutions: 70% usage

### Key Differentiators
| Feature | Fusion 360 | Industry Average |
|---------|-----------|------------------|
| Cloud Collaboration | Excellent | Moderate |
| Subscription Model | Flexible | Mixed |
| Learning Curve | Low | High |
| Update Frequency | Monthly | Quarterly |

---

## 2. Technical Capability Assessment

### Core Features Score: 8.5/10
- **Unified Platform**: Design, engineering, and manufacturing in one
- **Generative Design**: AI-driven design optimization
- **Simulation**: Integrated FEA capabilities
- **CAM**: 2.5 to 5-axis machining support

### Performance Metrics
\`\`\`
Model Complexity: Up to 10M faces (optimized)
Cloud Processing: Unlimited with credits
Collaboration: Real-time multi-user
Storage: Unlimited cloud storage
\`\`\`

---

## 3. ROI Analysis

### Initial Investment
- License Cost: $$ (Subscription-based)
- Implementation: 1-3 months
- Training: 20-40 hours per user

### Expected Returns
- **Design Cycle Reduction**: 20-30%
- **Collaboration Improvement**: 60%
- **Infrastructure Savings**: 40%
- **Time-to-Prototype**: 35% faster

---

## 4. Recommendations

### For Board/Executive Sponsors:
1. **Ideal for rapid prototyping** environments
2. **Lower barrier to entry** for teams
3. **Strong ROI** for smaller organizations
4. **Consider for satellite teams** and remote work

---

*Report generated by ResearchAI on ${new Date().toLocaleDateString()}*
`,
  default: `# Research & Analysis Report

### Executive Summary
This comprehensive analysis provides strategic insights and recommendations based on your selected parameters.

---

## 1. Overview

The selected configuration has been analyzed against industry benchmarks and best practices. Key findings indicate opportunities for optimization and strategic alignment.

---

## 2. Key Findings

### Strengths
- Strong market positioning
- Robust technical capabilities
- Scalable architecture

### Considerations
- Implementation timeline
- Training requirements
- Integration complexity

---

## 3. Recommendations

1. Proceed with phased implementation
2. Establish clear success metrics
3. Plan for change management
4. Monitor ROI throughout deployment

---

*Report generated by ResearchAI on ${new Date().toLocaleDateString()}*
`,
}

export const comparisonReports: Record<string, string> = {
  'autodesk-fusion': `## Comparison: Siemens NX vs Autodesk Fusion 360

### Head-to-Head Analysis

| Criteria | Siemens NX | Fusion 360 | Winner |
|----------|-----------|------------|--------|
| Enterprise Features | 9.5/10 | 7.5/10 | Siemens NX |
| Ease of Use | 7/10 | 9/10 | Fusion 360 |
| Cost Efficiency | 6/10 | 9/10 | Fusion 360 |
| Scalability | 9.5/10 | 7.5/10 | Siemens NX |
| Cloud Capabilities | 7/10 | 9.5/10 | Fusion 360 |
| PLM Integration | 10/10 | 6/10 | Siemens NX |

### Summary
- **Choose Siemens NX** for enterprise-scale manufacturing with complex PLM requirements
- **Choose Fusion 360** for agile teams, rapid prototyping, and cost-conscious organizations

### Migration Considerations
If transitioning between platforms, expect:
- 3-6 month transition period
- Data migration complexity: Medium
- Retraining requirement: 40+ hours
`,
  solidworks: `## Comparison: Siemens NX vs SolidWorks

### Head-to-Head Analysis

| Criteria | Siemens NX | SolidWorks | Winner |
|----------|-----------|------------|--------|
| Surface Modeling | 9.5/10 | 8/10 | Siemens NX |
| Assembly Management | 9/10 | 8.5/10 | Siemens NX |
| Simulation Depth | 9.5/10 | 7.5/10 | Siemens NX |
| User Community | 8/10 | 9.5/10 | SolidWorks |
| Documentation | 8.5/10 | 9/10 | SolidWorks |
| Learning Resources | 8/10 | 9.5/10 | SolidWorks |

### Summary
- **Choose Siemens NX** for advanced manufacturing and aerospace applications
- **Choose SolidWorks** for mid-market companies prioritizing ease of adoption

### Integration Notes
Both platforms offer good interoperability with standard file formats (STEP, IGES, Parasolid).
`,
  catia: `## Comparison: Siemens NX vs CATIA

### Head-to-Head Analysis

| Criteria | Siemens NX | CATIA | Winner |
|----------|-----------|-------|--------|
| Aerospace Features | 9/10 | 9.5/10 | CATIA |
| Automotive Design | 9.5/10 | 9/10 | Siemens NX |
| Surface Quality | 9/10 | 9.5/10 | CATIA |
| Manufacturing CAM | 9.5/10 | 8/10 | Siemens NX |
| License Cost | 6/10 | 5/10 | Siemens NX |
| Training Time | 6/10 | 5/10 | Siemens NX |

### Summary
- **Choose Siemens NX** for integrated CAD/CAM workflows and manufacturing focus
- **Choose CATIA** for complex surface modeling and aerospace-specific requirements

### Ecosystem Considerations
Both are enterprise-grade solutions with extensive partner networks.
`,
}
